// This file will be auto-generated by Supabase CLI
// For now, we'll define the types manually based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          avatar_url: string | null;
          phone_number: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          avatar_url?: string | null;
          phone_number?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          phone_number?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      todos: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          due_date: string | null;
          due_time: string | null;
          completed: boolean;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          due_date?: string | null;
          due_time?: string | null;
          completed?: boolean;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          due_date?: string | null;
          due_time?: string | null;
          completed?: boolean;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      todo_participants: {
        Row: {
          id: string;
          todo_id: string;
          user_id: string;
          role: 'owner' | 'viewer';
          created_at: string;
        };
        Insert: {
          id?: string;
          todo_id: string;
          user_id: string;
          role?: 'owner' | 'viewer';
          created_at?: string;
        };
        Update: {
          id?: string;
          todo_id?: string;
          user_id?: string;
          role?: 'owner' | 'viewer';
          created_at?: string;
        };
      };
      todo_metadata: {
        Row: {
          id: string;
          todo_id: string;
          type: 'phone' | 'link' | 'address' | 'note';
          label: string | null;
          value: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          todo_id: string;
          type: 'phone' | 'link' | 'address' | 'note';
          label?: string | null;
          value: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          todo_id?: string;
          type?: 'phone' | 'link' | 'address' | 'note';
          label?: string | null;
          value?: string;
          created_at?: string;
        };
      };
      todo_notifications: {
        Row: {
          id: string;
          todo_id: string;
          user_id: string;
          notify_at: string;
          notification_type: 'local' | 'push' | 'both';
          message: string | null;
          sent: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          todo_id: string;
          user_id: string;
          notify_at: string;
          notification_type?: 'local' | 'push' | 'both';
          message?: string | null;
          sent?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          todo_id?: string;
          user_id?: string;
          notify_at?: string;
          notification_type?: 'local' | 'push' | 'both';
          message?: string | null;
          sent?: boolean;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
